# Shawn Start
services:
  scampatrol:
    image: ghcr.io/shaniaong25026302/scampatrol:latest
    container_name: scampatrol

    restart: unless-stopped

    ports:
      - "80:3000"

    env_file:
      - .env
# Shawn End