# Shawn Start
services:
  scampatrol:
    image: ${IMAGE_NAME}
    container_name: scampatrol

    restart: unless-stopped

    ports:
      - "80:3000"

    env_file:
      - .env

    volumes:
      - /opt/scampatrol/uploads:/app/uploads
      - /opt/scampatrol/data:/app/data
# Shawn End